name: ci

on: [push, pull_request]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.3]
        platform:
          - { os: ubuntu, target: linux-x64 }
          # - { os: macos,  target: macos-arm64 }
    runs-on: ${{ matrix.platform.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just
      - name: setup
        run: just setup
      - name: lint
        run: just lint
      - name: test
        run: just test
      - name: doc
        run: just doc
      - name: package gem
        run: just gem
      - name: github release
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}-${{ steps.vars.outputs.sha_short }}
          draft: true
          files: |
            ./pkg/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
