name: ci

on: [push, pull_request]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.3]
        platform:
          - { os: ubuntu, target: linux-x64 }
        #   - { os: macos,  target: macos-arm64 }
    runs-on: ${{ matrix.platform.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: setup deps
        run: sudo apt-get install -y make 
      - name: setup
        run: make setup
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: doc
        run: make doc
      - name: package gem
        run: make gem
      - name: github release
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}-${{ steps.vars.outputs.sha_short }}
          draft: true
          files: |
            ./pkg/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
